### ISSUE TITLE
Terraform 0.12 support

### ISSUE THREAD

**Issue by EmakinaJoelDaleme** [connect-group/terraform-aws-ses-dashboard#3]
Hello,

Terraform 0.12 has been released so I'm wondering if there is any plan to upgrade this module so it would be compatible with the latest version of Terraform.

Thanks.

**Comment by 4dz** [comment]
Hi,  

The latest release (today) was tested with 0.12.12.  This module v1.0.6  is now available on the Terraform Modules Repository.  https://registry.terraform.io/modules/connect-group/ses-dashboard/aws/1.0.6

I've kept the syntax so that it will work with 0.10.4 and upwards.  However, it does require AWS Provider 2.11 or higher because earlier versions are not aware of Node 10.x.

Adam



Adam.
